# Generated by Django 3.2.13 on 2022-06-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('dob', models.DateTimeField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('register_password', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'register_info',
            },
        ),
    ]
