# Generated by Django 3.2.13 on 2022-07-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
    ]
